In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Dy_Industrial_Dataset 2.csv")

print("Shape:", df.shape)
print(df.head())
print(df.columns.tolist())

Shape: (2342, 22)
  Supplier_ID  Raw_Material_Availability  Supplier_Cost_per_Unit  \
0        S039                        726                   63.47   
1        S029                        320                   53.59   
2        S015                        706                   63.88   
3        S043                        918                   54.59   
4        S008                        635                   52.35   

   Lead_Time_Supplier  Reliability_Score Manufacturer_ID  Production_Capacity  \
0                   3               0.88            M002                 1116   
1                   6               0.73            M022                  877   
2                   8               0.80            M013                 1096   
3                   9               0.73            M012                 1137   
4                   3               0.99            M015                 1106   

   Machine_Utilization  Defect_Rate  Energy_Cost_per_Unit  ...  \
0                66.

In [2]:
print(df.dtypes)

Supplier_ID                     object
Raw_Material_Availability        int64
Supplier_Cost_per_Unit         float64
Lead_Time_Supplier               int64
Reliability_Score              float64
Manufacturer_ID                 object
Production_Capacity              int64
Machine_Utilization            float64
Defect_Rate                    float64
Energy_Cost_per_Unit           float64
Logistics_ID                    object
Distance_to_Market               int64
Fuel_Cost_per_km               float64
Delivery_Time                    int64
Vehicle_Utilization_Rate       float64
Retailer_ID                     object
Forecasted_Demand                int64
Actual_Demand                   object
Delivery_Satisfaction_Score    float64
Total_Cost                       int64
Delivery_Delay                   int64
Optimization_Label              object
dtype: object


In [3]:
missing = df.isnull().sum()

print(missing[missing > 0])

Series([], dtype: int64)


In [4]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(
    missing_percentage[missing_percentage > 0]
    .sort_values(ascending=False)
)

Series([], dtype: float64)


In [5]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0


In [6]:
print(df["Actual_Demand"].value_counts(dropna=False).head(20))

Actual_Demand
<function <lambda> at 0x0000020C0EA29DA0>    2342
Name: count, dtype: int64


In [7]:
print(df["Actual_Demand"].dtype)

object


In [8]:
df["Actual_Demand"] = pd.to_numeric(
    df["Actual_Demand"],
    errors="coerce"
)

In [9]:
print(
    "Missing Actual_Demand:",
    df["Actual_Demand"].isnull().sum()
)

Missing Actual_Demand: 2342


In [10]:
print(df["Actual_Demand"].head(20))
print(df["Actual_Demand"].unique()[:20])
print(df["Actual_Demand"].dtype)

print("\nForecasted Demand:")
print(df["Forecasted_Demand"].head(20))
print(df["Forecasted_Demand"].describe())

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: Actual_Demand, dtype: float64
[nan]
float64

Forecasted Demand:
0      856
1     1005
2      947
3     1078
4     1089
5      820
6      936
7      809
8      844
9     1048
10     829
11    1024
12     976
13     895
14     816
15     827
16     925
17    1072
18     986
19     941
Name: Forecasted_Demand, dtype: int64
count    2342.000000
mean      951.651580
std        87.577087
min       800.000000
25%       873.000000
50%       953.000000
75%      1029.000000
max      1099.000000
Name: Forecasted_Demand, dtype: float64


In [13]:

print(df.shape)
print(df.isnull().sum())

(2342, 21)
Supplier_ID                    0
Raw_Material_Availability      0
Supplier_Cost_per_Unit         0
Lead_Time_Supplier             0
Reliability_Score              0
Manufacturer_ID                0
Production_Capacity            0
Machine_Utilization            0
Defect_Rate                    0
Energy_Cost_per_Unit           0
Logistics_ID                   0
Distance_to_Market             0
Fuel_Cost_per_km               0
Delivery_Time                  0
Vehicle_Utilization_Rate       0
Retailer_ID                    0
Forecasted_Demand              0
Delivery_Satisfaction_Score    0
Total_Cost                     0
Delivery_Delay                 0
Optimization_Label             0
dtype: int64


In [14]:
numeric_cols = [
    "Raw_Material_Availability",
    "Supplier_Cost_per_Unit",
    "Lead_Time_Supplier",
    "Reliability_Score",
    "Production_Capacity",
    "Machine_Utilization",
    "Defect_Rate",
    "Energy_Cost_per_Unit",
    "Distance_to_Market",
    "Fuel_Cost_per_km",
    "Delivery_Time",
    "Vehicle_Utilization_Rate",
    "Forecasted_Demand",
    "Delivery_Satisfaction_Score",
    "Total_Cost",
    "Delivery_Delay"
]

print(df[numeric_cols].describe().T)

                              count          mean           std       min  \
Raw_Material_Availability    2342.0    661.489752    202.899654    300.00   
Supplier_Cost_per_Unit       2342.0     59.840376      5.729796     50.00   
Lead_Time_Supplier           2342.0      5.452178      2.306330      2.00   
Reliability_Score            2342.0      0.845517      0.085576      0.70   
Production_Capacity          2342.0   1001.889838    115.252648    800.00   
Machine_Utilization          2342.0     77.362562     10.272845     60.01   
Defect_Rate                  2342.0      1.750572      0.726444      0.50   
Energy_Cost_per_Unit         2342.0      2.530448      0.567315      1.50   
Distance_to_Market           2342.0    301.593510    115.298074    100.00   
Fuel_Cost_per_km             2342.0     11.579859      2.011682      8.00   
Delivery_Time                2342.0      3.554227      1.687025      1.00   
Vehicle_Utilization_Rate     2342.0     77.895371      9.999873     60.00   

In [15]:
for col in numeric_cols:
    negative_count = (df[col] < 0).sum()
    
    if negative_count > 0:
        print(col, "has", negative_count, "negative values")

Delivery_Delay has 731 negative values


In [16]:
percentage_cols = [
    "Reliability_Score",
    "Machine_Utilization",
    "Defect_Rate",
    "Vehicle_Utilization_Rate",
    "Delivery_Satisfaction_Score"
]

for col in percentage_cols:
    print("\n", col)
    print("Min:", df[col].min())
    print("Max:", df[col].max())


 Reliability_Score
Min: 0.7
Max: 1.0

 Machine_Utilization
Min: 60.01
Max: 94.96

 Defect_Rate
Min: 0.5
Max: 3.0

 Vehicle_Utilization_Rate
Min: 60.0
Max: 94.99

 Delivery_Satisfaction_Score
Min: 0.5
Max: 1.0


In [17]:
categorical_cols = [
    "Supplier_ID",
    "Manufacturer_ID",
    "Logistics_ID",
    "Retailer_ID",
    "Optimization_Label"
]

for col in categorical_cols:
    print("\n====================")
    print(col)
    print(df[col].value_counts().head(20))


Supplier_ID
Supplier_ID
S026    64
S037    59
S047    59
S033    59
S029    58
S049    58
S025    57
S035    55
S008    54
S032    53
S012    53
S045    52
S028    51
S023    50
S034    50
S017    50
S002    50
S044    50
S001    49
S006    49
Name: count, dtype: int64

Manufacturer_ID
Manufacturer_ID
M016    102
M013     99
M028     87
M017     85
M024     84
M005     83
M027     82
M021     82
M022     82
M026     80
M004     80
M020     80
M018     80
M007     80
M015     79
M008     79
M014     78
M006     78
M003     75
M002     75
Name: count, dtype: int64

Logistics_ID
Logistics_ID
L014    131
L004    130
L015    128
L005    127
L007    125
L019    124
L011    123
L016    122
L012    121
L008    120
L002    119
L018    118
L013    114
L020    112
L009    110
L017    107
L010    107
L006    104
L001    102
L003     98
Name: count, dtype: int64

Retailer_ID
Retailer_ID
R007    74
R030    71
R020    69
R006    68
R024    66
R040    66
R016    66
R005    65
R011    65
R025    64
R0

In [18]:
print(df["Optimization_Label"].value_counts())

Optimization_Label
Low       1248
Medium     879
High       215
Name: count, dtype: int64


In [20]:
print(df["Delivery_Delay"].describe())
print(df["Delivery_Delay"].value_counts().sort_index().head(20))
print(df["Delivery_Delay"].value_counts().sort_index().tail(20))

count    2342.000000
mean        0.578138
std         1.858424
min        -3.000000
25%        -1.000000
50%         1.000000
75%         2.000000
max         4.000000
Name: Delivery_Delay, dtype: float64
Delivery_Delay
-3    106
-2    258
-1    367
 0    394
 1    401
 2    414
 3    282
 4    120
Name: count, dtype: int64
Delivery_Delay
-3    106
-2    258
-1    367
 0    394
 1    401
 2    414
 3    282
 4    120
Name: count, dtype: int64


In [21]:
print(
    df.groupby("Optimization_Label")["Delivery_Delay"]
      .agg(["min", "mean", "median", "max"])
)

                    min      mean  median  max
Optimization_Label                            
High                 -3 -0.525581    -1.0    3
Low                  -3  0.992788     1.0    4
Medium               -3  0.259386     0.0    4


In [22]:
# DO NOT modify Delivery_Delay

print(df["Delivery_Delay"].value_counts().sort_index())

Delivery_Delay
-3    106
-2    258
-1    367
 0    394
 1    401
 2    414
 3    282
 4    120
Name: count, dtype: int64


In [23]:
numeric_cols = [
    "Raw_Material_Availability",
    "Supplier_Cost_per_Unit",
    "Lead_Time_Supplier",
    "Reliability_Score",
    "Production_Capacity",
    "Machine_Utilization",
    "Defect_Rate",
    "Energy_Cost_per_Unit",
    "Distance_to_Market",
    "Fuel_Cost_per_km",
    "Delivery_Time",
    "Vehicle_Utilization_Rate",
    "Forecasted_Demand",
    "Delivery_Satisfaction_Score",
    "Total_Cost",
    "Delivery_Delay"
]

print(df[numeric_cols].describe().T)

                              count          mean           std       min  \
Raw_Material_Availability    2342.0    661.489752    202.899654    300.00   
Supplier_Cost_per_Unit       2342.0     59.840376      5.729796     50.00   
Lead_Time_Supplier           2342.0      5.452178      2.306330      2.00   
Reliability_Score            2342.0      0.845517      0.085576      0.70   
Production_Capacity          2342.0   1001.889838    115.252648    800.00   
Machine_Utilization          2342.0     77.362562     10.272845     60.01   
Defect_Rate                  2342.0      1.750572      0.726444      0.50   
Energy_Cost_per_Unit         2342.0      2.530448      0.567315      1.50   
Distance_to_Market           2342.0    301.593510    115.298074    100.00   
Fuel_Cost_per_km             2342.0     11.579859      2.011682      8.00   
Delivery_Time                2342.0      3.554227      1.687025      1.00   
Vehicle_Utilization_Rate     2342.0     77.895371      9.999873     60.00   

In [24]:
# Make a copy before feature engineering
df_model = df.copy()

eps = 1e-6

# 1. Demand vs production capacity
df_model["Demand_Capacity_Ratio"] = (
    df_model["Forecasted_Demand"] /
    (df_model["Production_Capacity"] + eps)
)

# 2. Material coverage
df_model["Material_Demand_Coverage"] = (
    df_model["Raw_Material_Availability"] /
    (df_model["Forecasted_Demand"] + eps)
)

# 3. Material shortage amount
df_model["Material_Shortage"] = (
    df_model["Forecasted_Demand"] -
    df_model["Raw_Material_Availability"]
)

# 4. Supplier delay relative to lead time
df_model["Delay_LeadTime_Ratio"] = (
    df_model["Delivery_Delay"] /
    (df_model["Lead_Time_Supplier"] + eps)
)

# 5. Delivery time relative to supplier lead time
df_model["Delivery_LeadTime_Ratio"] = (
    df_model["Delivery_Time"] /
    (df_model["Lead_Time_Supplier"] + eps)
)

# 6. Quality risk
df_model["Quality_Risk"] = (
    df_model["Defect_Rate"] *
    (1 - df_model["Reliability_Score"])
)

# 7. Production pressure
df_model["Production_Pressure"] = (
    df_model["Machine_Utilization"] / 100
) * (
    df_model["Demand_Capacity_Ratio"]
)

# 8. Logistics burden
df_model["Logistics_Burden"] = (
    df_model["Distance_to_Market"] *
    df_model["Fuel_Cost_per_km"]
)

# 9. Supplier cost exposure
df_model["Supplier_Cost_Exposure"] = (
    df_model["Supplier_Cost_per_Unit"] *
    df_model["Forecasted_Demand"]
)

print(df_model.shape)

(2342, 30)


In [25]:
new_features = [
    "Demand_Capacity_Ratio",
    "Material_Demand_Coverage",
    "Material_Shortage",
    "Delay_LeadTime_Ratio",
    "Delivery_LeadTime_Ratio",
    "Quality_Risk",
    "Production_Pressure",
    "Logistics_Burden",
    "Supplier_Cost_Exposure"
]

print(df_model[new_features].describe().T)

                           count          mean          std           min  \
Demand_Capacity_Ratio     2342.0      0.963108     0.145852      0.671405   
Material_Demand_Coverage  2342.0      0.701409     0.227377      0.276243   
Material_Shortage         2342.0    290.161827   222.306472   -195.000000   
Delay_LeadTime_Ratio      2342.0      0.134565     0.495029     -1.499999   
Delivery_LeadTime_Ratio   2342.0      0.821565     0.629051      0.111111   
Quality_Risk              2342.0      0.270085     0.197548      0.000000   
Production_Pressure       2342.0      0.745208     0.152103      0.420031   
Logistics_Burden          2342.0   3487.735213  1469.518260    832.320000   
Supplier_Cost_Exposure    2342.0  56946.382028  7556.820982  40250.000000   

                                   25%           50%           75%  \
Demand_Capacity_Ratio         0.853462      0.951919      1.063179   
Material_Demand_Coverage      0.506649      0.697379      0.882340   
Material_Shortage  

In [26]:
supplier_features = [
    "Raw_Material_Availability",
    "Supplier_Cost_per_Unit",
    "Lead_Time_Supplier",
    "Reliability_Score",
    "Defect_Rate",
    "Energy_Cost_per_Unit",
    "Distance_to_Market",
    "Fuel_Cost_per_km",
    "Delivery_Time",
    "Vehicle_Utilization_Rate",
    "Forecasted_Demand",
    "Delivery_Satisfaction_Score",
    "Delivery_Delay",
    "Total_Cost",

    # engineered
    "Demand_Capacity_Ratio",
    "Material_Demand_Coverage",
    "Material_Shortage",
    "Delay_LeadTime_Ratio",
    "Delivery_LeadTime_Ratio",
    "Quality_Risk",
    "Logistics_Burden",
    "Supplier_Cost_Exposure"
]

In [27]:
print(
    df_model.groupby("Optimization_Label")[
        supplier_features
    ].mean().T
)

Optimization_Label                   High           Low        Medium
Raw_Material_Availability      409.423256    783.157051    550.401593
Supplier_Cost_per_Unit          57.810884     60.874111     58.869090
Lead_Time_Supplier               5.153488      5.571314      5.356086
Reliability_Score                0.860930      0.837620      0.852958
Defect_Rate                      1.088186      1.994223      1.566655
Energy_Cost_per_Unit             2.452326      2.551242      2.520034
Distance_to_Market             279.316279    309.433494    295.911263
Fuel_Cost_per_km                11.575256     11.636875     11.500034
Delivery_Time                    2.572093      3.921474      3.273038
Vehicle_Utilization_Rate        77.906093     77.972524     77.783208
Forecasted_Demand              949.995349    951.697115    951.992036
Delivery_Satisfaction_Score      0.789116      0.731058      0.763345
Delivery_Delay                  -0.525581      0.992788      0.259386
Total_Cost          

In [28]:
print(pd.crosstab(
    df_model["Optimization_Label"],
    pd.cut(
        df_model["Material_Demand_Coverage"],
        bins=[0, 0.5, 0.8, 1.0, np.inf],
        labels=["Critical", "Low", "Adequate", "Surplus"]
    ),
    normalize="index"
))

Material_Demand_Coverage  Critical       Low  Adequate   Surplus
Optimization_Label                                              
High                      0.823256  0.172093  0.004651  0.000000
Low                       0.056891  0.339744  0.415064  0.188301
Medium                    0.365188  0.509670  0.108077  0.017065


In [29]:
print(
    df_model.groupby("Optimization_Label")[
        "Material_Demand_Coverage"
    ].mean()
)

Optimization_Label
High      0.433936
Low       0.830870
Medium    0.583022
Name: Material_Demand_Coverage, dtype: float64


In [30]:
print(
    df_model.groupby("Optimization_Label")[
        "Material_Shortage"
    ].mean()
)

Optimization_Label
High      540.572093
Low       168.540064
Medium    401.590444
Name: Material_Shortage, dtype: float64


In [31]:
supplier_features = [
    "Raw_Material_Availability",
    "Supplier_Cost_per_Unit",
    "Lead_Time_Supplier",
    "Reliability_Score",
    "Defect_Rate",
    "Energy_Cost_per_Unit",
    "Distance_to_Market",
    "Fuel_Cost_per_km",
    "Delivery_Time",
    "Vehicle_Utilization_Rate",
    "Forecasted_Demand",
    "Delivery_Satisfaction_Score",
    "Delivery_Delay",
    "Total_Cost",

    "Material_Demand_Coverage",
    "Material_Shortage",
    "Delay_LeadTime_Ratio",
    "Delivery_LeadTime_Ratio",
    "Quality_Risk",
    "Logistics_Burden",
    "Supplier_Cost_Exposure"
]

In [32]:
X = df_model[supplier_features].copy()

y = df_model["Optimization_Label"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (2342, 21)
y shape: (2342,)

Target distribution:
Optimization_Label
Low       1248
Medium     879
High       215
Name: count, dtype: int64


In [33]:
print(X.isnull().sum())

Raw_Material_Availability      0
Supplier_Cost_per_Unit         0
Lead_Time_Supplier             0
Reliability_Score              0
Defect_Rate                    0
Energy_Cost_per_Unit           0
Distance_to_Market             0
Fuel_Cost_per_km               0
Delivery_Time                  0
Vehicle_Utilization_Rate       0
Forecasted_Demand              0
Delivery_Satisfaction_Score    0
Delivery_Delay                 0
Total_Cost                     0
Material_Demand_Coverage       0
Material_Shortage              0
Delay_LeadTime_Ratio           0
Delivery_LeadTime_Ratio        0
Quality_Risk                   0
Logistics_Burden               0
Supplier_Cost_Exposure         0
dtype: int64


In [34]:
print("Infinite values:")
print(np.isinf(X.select_dtypes(include=np.number)).sum().sum())

Infinite values:
0


In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Training: (1873, 21)
Testing: (469, 21)

Training target:
Optimization_Label
Low       998
Medium    703
High      172
Name: count, dtype: int64

Testing target:
Optimization_Label
Low       250
Medium    176
High       43
Name: count, dtype: int64


In [38]:
numeric_features = supplier_features

print(len(numeric_features))
print(numeric_features)

21
['Raw_Material_Availability', 'Supplier_Cost_per_Unit', 'Lead_Time_Supplier', 'Reliability_Score', 'Defect_Rate', 'Energy_Cost_per_Unit', 'Distance_to_Market', 'Fuel_Cost_per_km', 'Delivery_Time', 'Vehicle_Utilization_Rate', 'Forecasted_Demand', 'Delivery_Satisfaction_Score', 'Delivery_Delay', 'Total_Cost', 'Material_Demand_Coverage', 'Material_Shortage', 'Delay_LeadTime_Ratio', 'Delivery_LeadTime_Ratio', 'Quality_Risk', 'Logistics_Burden', 'Supplier_Cost_Exposure']


In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [40]:
preprocessor = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [41]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=500,
        max_depth=12,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

In [42]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('scaler', StandardScaler())])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=12,
                                        min_samples_leaf=3, n_estimators=500,
                                        n_jobs=-1, random_state=42))])

In [43]:
y_pred_rf = rf_model.predict(X_test)

print(y_pred_rf[:20])

['Medium' 'Low' 'Low' 'Low' 'Low' 'Medium' 'Medium' 'Low' 'Low' 'Low'
 'Medium' 'High' 'High' 'Low' 'Low' 'Low' 'Low' 'Medium' 'Low' 'High']


In [44]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:",
      accuracy_score(y_test, y_pred_rf))

print("Precision:",
      precision_score(
          y_test,
          y_pred_rf,
          average="weighted"
      ))

print("Recall:",
      recall_score(
          y_test,
          y_pred_rf,
          average="weighted"
      ))

print("F1:",
      f1_score(
          y_test,
          y_pred_rf,
          average="weighted"
      ))

Accuracy: 0.9019189765458422
Precision: 0.9027361235751263
Recall: 0.9019189765458422
F1: 0.8998381560612209


In [45]:
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        labels=["Low", "Medium", "High"]
    )
)


Classification Report:
              precision    recall  f1-score   support

         Low       0.94      0.95      0.95       250
      Medium       0.85      0.90      0.87       176
        High       0.90      0.63      0.74        43

    accuracy                           0.90       469
   macro avg       0.90      0.83      0.85       469
weighted avg       0.90      0.90      0.90       469



In [46]:
print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_rf,
        labels=["Low", "Medium", "High"]
    )
)


Confusion Matrix:
[[238  12   0]
 [ 15 158   3]
 [  0  16  27]]


In [47]:
report = classification_report(
    y_test,
    y_pred_rf,
    labels=["Low", "Medium", "High"],
    output_dict=True
)

print(
    "HIGH-risk recall:",
    report["High"]["recall"]
)

HIGH-risk recall: 0.627906976744186


In [48]:
from xgboost import XGBClassifier

In [49]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

print(label_encoder.classes_)

['High' 'Low' 'Medium']


In [50]:
xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="multi:softprob",
        num_class=3,
        eval_metric="mlogloss",
        random_state=42
    ))
])

In [51]:
xgb_model.fit(
    X_train,
    y_train_encoded
)

Pipeline(steps=[('preprocessor',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('scaler', StandardScaler())])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.8, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='mlogloss',
                               f...ture_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=400, n_jobs=None, num_class=3, ...))])

In [52]:
y_pred_xgb_encoded = xgb_model.predict(X_test)

y_pred_xgb = label_encoder.inverse_transform(
    y_pred_xgb_encoded.astype(int)
)

In [53]:
print(
    classification_report(
        y_test,
        y_pred_xgb,
        labels=["Low", "Medium", "High"]
    )
)

              precision    recall  f1-score   support

         Low       0.97      0.98      0.97       250
      Medium       0.89      0.95      0.92       176
        High       0.97      0.67      0.79        43

    accuracy                           0.94       469
   macro avg       0.94      0.87      0.90       469
weighted avg       0.94      0.94      0.94       469



In [55]:
print("X shape:", X.shape)
print("y shape:", y.shape)
print(y.value_counts())

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

X shape: (2342, 21)
y shape: (2342,)
Optimization_Label
Low       1248
Medium     879
High       215
Name: count, dtype: int64
Training: (1873, 21)
Testing: (469, 21)
Optimization_Label
Low       998
Medium    703
High      172
Name: count, dtype: int64
Optimization_Label
Low       250
Medium    176
High       43
Name: count, dtype: int64


In [56]:
results_df = X_test.copy()

results_df["Actual_Risk"] = y_test.values
results_df["Predicted_Risk"] = y_pred_xgb

missed_high = results_df[
    (results_df["Actual_Risk"] == "High") &
    (results_df["Predicted_Risk"] != "High")
]

print("Missed High-risk cases:", len(missed_high))

print(
    missed_high[
        [
            "Raw_Material_Availability",
            "Material_Demand_Coverage",
            "Material_Shortage",
            "Reliability_Score",
            "Defect_Rate",
            "Delivery_Delay",
            "Delivery_Time",
            "Lead_Time_Supplier"
        ]
    ]
)

Missed High-risk cases: 14
      Raw_Material_Availability  Material_Demand_Coverage  Material_Shortage  \
1463                        322                  0.382878                519   
1798                        373                  0.378680                612   
583                         572                  0.524771                518   
2070                        617                  0.633470                357   
444                         489                  0.451107                595   
2263                        719                  0.724068                274   
1570                        302                  0.349537                562   
686                         504                  0.609432                323   
1279                        408                  0.399217                614   
259                         378                  0.464945                435   
12                          633                  0.648566                343   
1839         

In [57]:
xgb_probabilities = xgb_model.predict_proba(X_test)

print(xgb_probabilities[:5])

[[5.9884327e-04 9.3604429e-03 9.9004072e-01]
 [3.6504832e-07 9.9998891e-01 1.0758626e-05]
 [1.9607753e-05 9.9770975e-01 2.2705947e-03]
 [6.8243949e-05 9.9886644e-01 1.0653202e-03]
 [4.2413178e-04 5.9084988e-01 4.0872601e-01]]


In [58]:
high_index = list(label_encoder.classes_).index("High")

missed_indices = X_test.index[
    (y_test == "High") &
    (pd.Series(y_pred_xgb, index=X_test.index) != "High")
]

print(
    pd.DataFrame({
        "Actual": y_test.loc[missed_indices],
        "Predicted": pd.Series(
            y_pred_xgb,
            index=X_test.index
        ).loc[missed_indices],
        "High_Probability": xgb_probabilities[
            [X_test.index.get_loc(i) for i in missed_indices],
            high_index
        ]
    })
)

     Actual Predicted  High_Probability
1463   High    Medium          0.183821
1798   High    Medium          0.070646
583    High    Medium          0.421529
2070   High    Medium          0.014255
444    High    Medium          0.396051
2263   High    Medium          0.011749
1570   High    Medium          0.026893
686    High    Medium          0.030750
1279   High    Medium          0.026716
259    High    Medium          0.445017
12     High    Medium          0.137089
1839   High    Medium          0.023225
2135   High    Medium          0.436706
2150   High    Medium          0.335587


In [59]:
y_binary = (
    df_model["Optimization_Label"] == "High"
).astype(int)

print(y_binary.value_counts())

Optimization_Label
0    2127
1     215
Name: count, dtype: int64


In [60]:
X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X,
    y_binary,
    test_size=0.20,
    random_state=42,
    stratify=y_binary
)

print(y_train_b.value_counts())
print(y_test_b.value_counts())

Optimization_Label
0    1701
1     172
Name: count, dtype: int64
Optimization_Label
0    426
1     43
Name: count, dtype: int64


In [61]:
high_count = (y_train_b == 1).sum()
non_high_count = (y_train_b == 0).sum()

scale_pos_weight = non_high_count / high_count

print("scale_pos_weight:", scale_pos_weight)

scale_pos_weight: 9.88953488372093


In [62]:
high_risk_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss",
        random_state=42
    ))
])

In [63]:
high_risk_model.fit(
    X_train_b,
    y_train_b
)

Pipeline(steps=[('preprocessor',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('scaler', StandardScaler())])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.8, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='logloss',
                               fe...s=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=400, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [64]:
high_prob = high_risk_model.predict_proba(X_test_b)[:, 1]

In [65]:
high_pred = (high_prob >= 0.50).astype(int)

In [66]:
from sklearn.metrics import classification_report, confusion_matrix

print(
    classification_report(
        y_test_b,
        high_pred,
        target_names=["Not High", "High"]
    )
)

print(
    confusion_matrix(
        y_test_b,
        high_pred
    )
)

              precision    recall  f1-score   support

    Not High       0.99      0.99      0.99       426
        High       0.91      0.93      0.92        43

    accuracy                           0.99       469
   macro avg       0.95      0.96      0.96       469
weighted avg       0.99      0.99      0.99       469

[[422   4]
 [  3  40]]


In [67]:
leakage_test_features = [
    "Raw_Material_Availability",
    "Supplier_Cost_per_Unit",
    "Lead_Time_Supplier",
    "Reliability_Score",
    "Defect_Rate",
    "Energy_Cost_per_Unit",
    "Distance_to_Market",
    "Fuel_Cost_per_km",
    "Delivery_Time",
    "Vehicle_Utilization_Rate",
    "Forecasted_Demand",
    "Delivery_Satisfaction_Score",
    "Delivery_Delay",
    "Total_Cost",

    # REMOVE these for the leakage test:
    # "Material_Demand_Coverage",
    # "Material_Shortage",

    "Delay_LeadTime_Ratio",
    "Delivery_LeadTime_Ratio",
    "Quality_Risk",
    "Logistics_Burden",
    "Supplier_Cost_Exposure"
]

In [68]:
X_leakage_test = df_model[leakage_test_features].copy()

In [69]:
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_leakage_test,
    y_binary,
    test_size=0.20,
    random_state=42,
    stratify=y_binary
)

In [70]:
preprocessor_l = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [71]:
high_risk_model_l = Pipeline([
    ("preprocessor", preprocessor_l),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss",
        random_state=42
    ))
])

high_risk_model_l.fit(X_train_l, y_train_l)

Pipeline(steps=[('preprocessor',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('scaler', StandardScaler())])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.8, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='logloss',
                               fe...s=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=400, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [72]:
high_prob_l = high_risk_model_l.predict_proba(X_test_l)[:, 1]

high_pred_l = (high_prob_l >= 0.50).astype(int)

In [73]:
print(
    classification_report(
        y_test_l,
        high_pred_l,
        target_names=["Not High", "High"]
    )
)

print(
    confusion_matrix(
        y_test_l,
        high_pred_l
    )
)

              precision    recall  f1-score   support

    Not High       1.00      0.98      0.99       426
        High       0.85      0.95      0.90        43

    accuracy                           0.98       469
   macro avg       0.92      0.97      0.95       469
weighted avg       0.98      0.98      0.98       469

[[419   7]
 [  2  41]]


In [74]:
import joblib

joblib.dump(
    xgb_model,
    "supplier_risk_classification_model.joblib"
)

['supplier_risk_classification_model.joblib']

In [75]:
joblib.dump(
    high_risk_model_l,
    "supplier_high_risk_model.joblib"
)

['supplier_high_risk_model.joblib']

In [76]:
supplier_model = joblib.load(
    "supplier_risk_classification_model.joblib"
)

high_risk_model = joblib.load(
    "supplier_high_risk_model.joblib"
)